// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import (
	"io/ioutil"
	"log"
	"os"

	"github.com/swaggo/swag"
)

var docTemplate string


func init() {
	data, err := ioutil.ReadFile("./src/docs/swagger.json")
    if err != nil {
        log.Fatalf("Failed to read swagger.json: %v", err)
    }
    docTemplate = string(data)


	var SwaggerInfo = &swag.Spec{
		Version:          "1.0",
		Host:             os.Getenv("API_HOST"), 
		BasePath:         "/",
		Schemes:          []string{"https"},
		Title:            "Go CRUD API",
		Description:      "Simple CRUD API using Go, GORM, PostgreSQL, and Gin",
		InfoInstanceName: "swagger",
		SwaggerTemplate:  docTemplate,
		LeftDelim:        "{{",
		RightDelim:       "}}",
	}

	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
